<a href="https://colab.research.google.com/github/andand0912837465-cell/2026-1-BDA/blob/main/03w_python_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.linspace(2,3)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [3]:
(3-1)/(50-1)

0.04081632653061224

In [4]:
np.linspace(2,3,2)

array([2., 3.])

In [5]:
np.linspace(2,3,3)

array([2. , 2.5, 3. ])

In [7]:
np.linspace(2,3,3,retstep = True)

(array([2. , 2.5, 3. ]), np.float64(0.5))

In [11]:
a=np.linspace(2,3,3,retstep = True)
float(a[1])

0.5

In [15]:
np.linspace(2,3,3,retstep = True,endpoint = False)

(array([2.        , 2.33333333, 2.66666667]), np.float64(0.3333333333333333))

###numpy 주요함수

In [16]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [17]:
np.zeros(2, dtype=int)

array([0, 0])

In [18]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [19]:
np.zeros(2,3)

TypeError: Cannot interpret '3' as a data type

In [20]:
np.full([2,3],10)

array([[10, 10, 10],
       [10, 10, 10]])

In [21]:
np.full([2,3],(1,2,3))

array([[1, 2, 3],
       [1, 2, 3]])

In [22]:
np.full([2,3],(1,2))

ValueError: could not broadcast input array from shape (2,) into shape (2,3)

In [23]:
np.full([3,4],range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [27]:
np.full([4,3], fill_value = np.arange(4).reshape(4,1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [28]:
np.empty

<function numpy.empty>

In [29]:
np.empty([2,2])

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [31]:
np.empty([2,3],dtype=int)

array([[461401274,         0,         0],
       [        0,         0,         0]])

In [33]:
import numpy as np
a=np.arange(3)
a

array([0, 1, 2])

In [34]:
print (a + 2)
print(a - 2)
print(a* 2)
print(a / 2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


In [39]:
a=np.array([[10, 20], [5, 8], [1, 2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [40]:
a.sum()

np.int64(46)

In [41]:
a.sum(axis=0)

array([16, 30])

In [42]:
a.sum(axis=1)

array([30, 13,  3])

In [47]:
import numpy as np
print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

46
[16 30]
[30 13  3]


In [49]:
a = np.array([[3, 5, 8], [1, 2, 3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [50]:
# 1차원으로 펼쳐서 계산
a.cumsum()

array([ 3,  8, 16, 17, 19, 22])

In [53]:
# 시험예상, 행을 따라 세로로 합산
a.cumsum(axis=0)

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [54]:
# 시험예상a.cumsum(axis=1)

In [55]:
import numpy as np
a = np.power(np.arange(10), 2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [56]:
print(a[3])
print(a[-2])

9
64


In [57]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [58]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [61]:
# 전체 배열을 역순으로
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [60]:
# 2단계씩 건너뛰며 역순으로
a[::-2]

[81 49 25  9  1]


In [62]:
a[2:5] = -100
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [63]:
a[2:5] = [-5, -5, -5]
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81])

In [64]:
a[2:5] = [-5, -5]

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [65]:
a[2:5] = -10
a

array([  0,   1, -10, -10, -10,  25,  36,  49,  64,  81])

#2차원 배열

In [66]:
a = np.arange(30).reshape(5,6) # 0부터 29까지의 숫자로 5행 6열 2차원 배열 생성
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [67]:
a[3] # 인덱스 3에 해당하는 네 번째 행 전체를 선택

array([18, 19, 20, 21, 22, 23])

In [68]:
a[-1] # 마지막 행 전체를 선택

array([24, 25, 26, 27, 28, 29])

In [69]:
a[-2,:] # 뒤에서 두 번째 행 전체를 선택 (':'은 해당 축의 모든 요소를 의미)

array([18, 19, 20, 21, 22, 23])

In [70]:
a[-2,] # 뒤에서 두 번째 행 전체를 선택 (a[-2,:]와 동일한 결과)

array([18, 19, 20, 21, 22, 23])

In [71]:
a[2:4] # 인덱스 2부터 3까지의 행(세 번째 행, 네 번째 행)을 선택

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [72]:
a[1:5:2] # 인덱스 1부터 4까지의 행 중 2단계씩 건너뛰어 선택 (두 번째 행, 네 번째 행)

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [76]:
a[,1]

SyntaxError: invalid syntax (3819423678.py, line 1)

In [74]:
a[:,1] # 모든 행에서 인덱스 1에 해당하는 두 번째 열을 선택

array([ 1,  7, 13, 19, 25])

In [75]:
a[:,1:6] # 모든 행에서 인덱스 1부터 5까지의 열을 선택 (두 번째 열부터 마지막 열까지)

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [77]:
a = np.arange(30).reshape(5,6) # 0부터 29까지의 숫자로 5행 6열 2차원 배열 생성
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [78]:
a[:,::2] # 모든 행에서 짝수 번째 열만 선택 (0, 2, 4열)

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [79]:
a[2,4] # 인덱스 (2,4)에 해당하는 단일 요소 선택 (세 번째 행, 다섯 번째 열)

np.int64(16)

In [80]:
a[2][4] # 행을 먼저 선택한 후 해당 행에서 열을 선택 (a[2,4]와 동일)

np.int64(16)

In [81]:
a[1:3,2:5] # 행 인덱스 1부터 2까지(두 번째, 세 번째 행)와 열 인덱스 2부터 4까지(세 번째, 네 번째, 다섯 번째 열)를 선택

array([[ 8,  9, 10],
       [14, 15, 16]])

In [82]:
a[:,:] # 배열 전체를 선택 (모든 행, 모든 열)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [83]:
a[:,] # 배열 전체를 선택 (a[:,:]와 동일)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [84]:
a[:] # 배열 전체를 선택 (a[:,:]와 동일)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [85]:
a[::-1,::-1] # 배열을 행과 열 모두 역순으로 뒤집기

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [87]:
# 마지막 행과 열을 제외한 배열 반환
a[:-1,:-1] # 마지막 행과 마지막 열을 제외한 모든 요소를 선택

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

#3차원 배열

In [98]:
a=np.arange(24).reshape(2,3,4) # 0부터 23까지의 숫자로 2층 3행 4열 3차원 배열 생성
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [99]:
a[1] # 인덱스 1에 해당하는 두 번째 '층'(axis=0) 전체를 선택

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [100]:
a[:,1] # 모든 '층'에서 인덱스 1에 해당하는 두 번째 '행'(axis=1) 전체를 선택

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [101]:
a[:,1,1] # 모든 '층'에서 인덱스 1의 '행', 그리고 인덱스 1의 '열'(axis=2)에 해당하는 요소들을 선택

array([ 5, 17])

In [102]:
a[:,:,1] # 모든 '층'과 모든 '행'에서 인덱스 1에 해당하는 두 번째 '열' 전체를 선택

array([[ 1,  5,  9],
       [13, 17, 21]])

In [103]:
a[..., 1] # '...'은 생략된 모든 차원을 의미합니다. 마지막 차원의 인덱스 1을 선택 (a[:,:,1]과 동일)

array([[ 1,  5,  9],
       [13, 17, 21]])

In [104]:
a[1, ..., 1] # 첫 번째 차원의 인덱스 1(두 번째 층)에서, 생략된 중간 차원들을 거쳐 마지막 차원의 인덱스 1을 선택

array([13, 17, 21])

In [105]:
a[0, ...] # 첫 번째 차원의 인덱스 0(첫 번째 층)을 선택하고 나머지 차원은 모두 포함 (a[0,:,:] 또는 a[0]과 동일)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [106]:
a[0] # 첫 번째 차원의 인덱스 0(첫 번째 층) 전체를 선택 (a[0,...]과 동일)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
a=np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [109]:
b=a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [110]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [112]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [114]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [115]:
b=np.arange(1,13).reshape(3,2,2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [116]:
b.T

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [118]:
np.transpose(b,(0,1,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [119]:
np.transpose(b,(2,1,0))

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [120]:
np.transpose(b,(0,2,1))

array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]])

In [125]:

x = np.array([[7, 8, 9]])
x

array([[7, 8, 9]])

In [126]:
y = np.swapaxes(x, 0, 1)
y

array([[7],
       [8],
       [9]])

In [127]:
y = np.swapaxes(x, 1, 0)
y

array([[7],
       [8],
       [9]])

In [128]:
y[0, 0] = 10
y

array([[10],
       [ 8],
       [ 9]])

In [129]:
import numpy as np

X = np.arange(8).reshape(2, 2, 2)
X

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [130]:
np.swapaxes(X, 0, 2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [131]:
np.transpose(X, (2, 1, 0))

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [132]:
import numpy as np

org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [133]:
v = org.view()
v

array([0, 1, 2, 3, 4])

In [134]:
v[2] = -200
v

array([   0,    1, -200,    3,    4])

In [135]:
org

array([   0,    1, -200,    3,    4])

In [136]:
import numpy as np

org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [137]:
c = org.copy()
c

array([0, 1, 2, 3, 4])

In [138]:
c[2] = 200
c

array([  0,   1, 200,   3,   4])

In [139]:
org

array([0, 1, 2, 3, 4])

In [140]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [141]:
y = x.reshape(2, 3)
y

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
print( x.base)

In [142]:
y.base

array([0, 1, 2, 3, 4, 5])

In [143]:
import numpy as np
x = np.arange(6)
y = x.reshape(2, 3)

In [144]:
z = y.transpose()
z.base

array([0, 1, 2, 3, 4, 5])

In [145]:
c = z.copy()
print(c.base)

None


In [146]:
list_example = list(range(8))
list_example

[0, 1, 2, 3, 4, 5, 6, 7]

In [147]:
list_example[3:5] = [30, 40, 50]
list_example

[0, 1, 2, 30, 40, 50, 5, 6, 7]

In [148]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [149]:
x[3:5] = [30, 40]
x

array([ 0,  1,  2, 30, 40,  5,  6,  7])

In [150]:
x[3:5] = [30, 40, 50]
x

ValueError: could not broadcast input array from shape (3,) into shape (2,)

#브로드 케스팅

In [151]:
import numpy as np

a = np.array([3, 4, 5])
b = np.array([8, 7, 6])
a+b

array([11, 11, 11])

In [152]:
a = np.array([3, 4, 5, 7])
b = np.array([8, 7, 6])
a*b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [153]:
import numpy as np

x = np.arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [154]:
y = np.arange(-1, 2)
y

array([-1,  0,  1])

In [155]:
x * y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [156]:
x + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [157]:
import numpy as np

x = np.arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [158]:
y = np.arange(3, 10, 3).reshape(3, 1)
y

array([[3],
       [6],
       [9]])

In [161]:
# 소수점 이하 자릿수를 2자리로 설정
np.set_printoptions(precision=2)
x/y

array([[0.33, 0.67, 1.  ],
       [0.67, 0.83, 1.  ],
       [0.78, 0.89, 1.  ]])

In [160]:
x-y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [162]:
import numpy as np

x = np.arange(1, 4)
x

array([1, 2, 3])

In [163]:
y = np.arange(1, 4).reshape(3, 1)
y

array([[1],
       [2],
       [3]])

In [164]:
x * y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [165]:
x / y

array([[1.  , 2.  , 3.  ],
       [0.5 , 1.  , 1.5 ],
       [0.33, 0.67, 1.  ]])

In [166]:
import numpy as np

x = np.arange(0, 10, 3).reshape(4, 1)
x

array([[0],
       [3],
       [6],
       [9]])

In [167]:
y = np.arange(1, 3)
y

array([1, 2])

In [168]:
x * y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [169]:
x + y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [170]:
import numpy as np
from numpy import array

x = array([0, 10, 20, 30])
x

array([ 0, 10, 20, 30])

In [171]:
np.newaxis is None

True

In [172]:
a = x[None,:]
a

array([[ 0, 10, 20, 30]])

In [173]:
a = x[np.newaxis,:]
a

array([[ 0, 10, 20, 30]])

In [174]:
a = x[:, np.newaxis]
a


array([[ 0],
       [10],
       [20],
       [30]])

In [176]:
a.shape

(4, 1)

In [ ]:
a = x[:,np.newaxis]
a

#고급 색인

In [177]:
import numpy as np
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [178]:
print(x[1])

1


In [179]:
print(x[:5])

[0 1 2 3 4]


In [180]:
print(x[[2]])

[2]


In [181]:
print(x[[2, 3]])

[2 3]


In [182]:
x[[2, 3, 5, 8]]

array([2, 3, 5, 8])

In [183]:
x[np.array([5, 3, 4, 8])]

array([5, 3, 4, 8])

In [186]:
from numpy import arange

x = arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [184]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [185]:
x[0]

np.int64(0)

In [187]:
x[0, 1]

np.int64(1)

In [188]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [189]:
x[, 2:8]

SyntaxError: invalid syntax (2523553509.py, line 2)

In [190]:
x[[0], [1]]

array([1])

In [191]:
x[[0], [1]]

array([1])

In [196]:
x[[0, 1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [193]:
x[:, [5, 4]]

array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [194]:
x[[1, 3]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [197]:
x[[1, 3],:]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [198]:
import numpy as np

x[np.array([0, 2, 4]), 1]

array([ 1, 17, 33])

In [199]:
print(x[0, 1])
print(x[2, 1])
print(x[4, 1])

1
17
33


In [200]:
x[np.array([0, 2, 4]), :2]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [202]:
from numpy import array
x[np.array([0, 2, 4]), np.array([0, 1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [203]:
from numpy import arange

a = arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [204]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [211]:
a[[2,3]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [212]:
a[np.arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [214]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [207]:
a[np.arange(2, 4)][:, [1, 0]]

array([[17, 16],
       [25, 24]])

In [208]:
a[np.arange(2, 5)][:, [1, 0, 3, 5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [209]:
a[np.arange(2, 5)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [217]:
a[[2,-3,-4]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [223]:
a[[2,-3,-4][:,-1,-2,-3,-4,-5,-6,-7]]

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
/tmp/ipykernel_739/110646928.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a[[2,-3,-4][:,-1,-2,-3,-4,-5,-6,-7]]


TypeError: list indices must be integers or slices, not tuple

In [210]:
a[np.arange(2, 5)][:, np.arange(-1, -8, -1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])