<a href="https://colab.research.google.com/github/andand0912837465-cell/2026-1-BDA/blob/main/04w_arrary_stack_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

a=np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
b=np.arange(1, 5)
b

array([1, 2, 3, 4])

In [9]:
np.column_stack((a,c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  2],
       [ 9, 10, 11, 12,  3]])

In [7]:
np.row_stack((a, b))

/tmp/ipykernel_1822/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [10]:
np.vstack((a, b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [11]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

result= np.c_[a,b]
print(result)

[[1 4]
 [2 5]
 [3 6]]


In [13]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])


In [14]:
np.c_[a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [15]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
x = np.array([[1,2,3]])
y = np.array([[4,5,6]])

In [17]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [18]:
np.column_stack((x, y))

array([[1, 2, 3, 4, 5, 6]])

In [19]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [20]:
np.column_stack((x, 10, 20, y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [21]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

In [22]:
np.r_[a,b]

array([1, 2, 3, 4, 5, 6])

In [30]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [31]:
np.row_stack((a,b))

/tmp/ipykernel_1822/1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
np.r_[a,0,0, b]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [34]:
np.r_[3:10:3,[0]*2,5,6]

array([3, 6, 9, 0, 0, 5, 6])

In [36]:
np.r_[-1:1:6j, [0]*2, 5, 6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [37]:
np.linspace(-1, 1, 6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [38]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [39]:
np.r_[a, a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [40]:
np.r_['0', a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [41]:
np.r_['-1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [42]:
np.r_['1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

##배열분리

In [44]:
numpy.split(ary, indices_or_sections, axis=0)

NameError: name 'ary' is not defined

In [47]:
import numpy as np
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [46]:
s = np.split(x, 3)
s

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [48]:
import numpy as np
y = np.arange(10, 61, 10)
y

array([10, 20, 30, 40, 50, 60])

In [49]:
np.split(y, [2, 3, 4, 6])

[array([10, 20]),
 array([30]),
 array([40]),
 array([50, 60]),
 array([], dtype=int64)]

In [50]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.hsplit(a, 3)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [53]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [54]:
np.split(a, 3, axis=1)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [55]:
np.split(a, 4, axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [56]:
b = np.arange(24).reshape(6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [57]:
np.split(b, 3, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [59]:
np.split(b,[2,4,6],axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([], shape=(0, 4), dtype=int64)]

In [60]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [61]:
np.split(a, [3,5,7], axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11],
        [19, 20, 21, 22, 23]])]

In [62]:
b = np.arange(24).reshape(6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [63]:
np.split(b,3,axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [64]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.hsplit(a,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [66]:
np.hsplit(a,[2,5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [67]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [68]:
np.hsplit(a, (3, 5, 8))

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6,  7],
        [17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [69]:
a[:, :3]

array([[ 0,  1,  2],
       [12, 13, 14]])

In [70]:
a[:, 8:]

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])

In [71]:
a= np.arange(18).reshape(6,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [72]:
np.vsplit(a, 3)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [73]:
np.vsplit(a, 4)

ValueError: array split does not result in an equal division

In [74]:
np.vsplit(a, (1, 4, 6))

[array([[0, 1, 2]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]]),
 array([], shape=(0, 3), dtype=int64)]

In [75]:
a[:1,:]

array([[0, 1, 2]])

In [76]:
a[4:6,:]

array([[12, 13, 14],
       [15, 16, 17]])

In [77]:
a[6:,:]

array([], shape=(0, 3), dtype=int64)

In [83]:
np.split(x,2,axis=0)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [81]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [82]:
np.vsplit(x,2)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [85]:
x[:1,:,:]

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]])

In [86]:
x[1:3]

array([[[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [87]:
x[3:]

array([[[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [84]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [88]:
np.vsplit(x,[1,3])

[array([[[0, 1],
         [2, 3],
         [4, 5],
         [6, 7]]]),
 array([[[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],
 
        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]]),
 array([[[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [89]:
x=np.arange(32).reshape(4,4,2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [90]:
np.hsplit(x,2)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [91]:
np.split(x,2,axis=1)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [92]:
x=np.arange(32).reshape(4,4,2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [93]:
np.hsplit(x,[1,3])

[array([[[ 0,  1]],
 
        [[ 8,  9]],
 
        [[16, 17]],
 
        [[24, 25]]]),
 array([[[ 2,  3],
         [ 4,  5]],
 
        [[10, 11],
         [12, 13]],
 
        [[18, 19],
         [20, 21]],
 
        [[26, 27],
         [28, 29]]]),
 array([[[ 6,  7]],
 
        [[14, 15]],
 
        [[22, 23]],
 
        [[30, 31]]])]

##numpy의 난수와 다양한 함수

In [95]:
import numpy as np

rg = np.random.default_rng(12345)
rg

Generator(PCG64) at 0x7C82A1D99FC0

In [96]:
r = rg.random()
r

0.22733602246716966

In [97]:
rg.random(5)

array([0.31675834, 0.79736546, 0.67625467, 0.39110955, 0.33281393])

In [100]:
rg.random((4, 3))

array([[0.59830875, 0.18673419, 0.67275604],
       [0.94180287, 0.24824571, 0.94888115],
       [0.66723745, 0.09589794, 0.44183967],
       [0.88647992, 0.6974535 , 0.32647286]])

In [101]:
import numpy as np

rg=np.random.default_rng(12345)
r = rg.integers(low=0, high=10, size=3)
r

array([6, 2, 7])

In [102]:
rg.integers(1,7,(3,4))

array([[2, 2, 5, 4],
       [5, 6, 3, 6],
       [2, 4, 4, 2]])

In [104]:
import numpy as np

rg = np.random.default_rng(seed=42)
rg.standard_normal(10)

array([ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472, -1.95103519,
       -1.30217951,  0.1278404 , -0.31624259, -0.01680116, -0.85304393])

In [106]:
rg.standard_normal((4,3))

array([[ 0.87939797,  0.77779194,  0.0660307 ],
       [ 1.12724121,  0.46750934, -0.85929246],
       [ 0.36875078, -0.9588826 ,  0.8784503 ],
       [-0.04992591, -0.18486236, -0.68092954]])

In [107]:
rg.standard_normal(500)

array([ 1.22254134e+00, -1.54529482e-01, -4.28327822e-01, -3.52133550e-01,
        5.32309186e-01,  3.65444064e-01,  4.12732612e-01,  4.30821003e-01,
        2.14164760e+00, -4.06415016e-01, -5.12242729e-01, -8.13772728e-01,
        6.15979423e-01,  1.12897229e+00, -1.13947458e-01, -8.40156477e-01,
       -8.24481216e-01,  6.50592788e-01,  7.43254171e-01,  5.43154268e-01,
       -6.65509707e-01,  2.32161323e-01,  1.16685809e-01,  2.18688597e-01,
        8.71428778e-01,  2.23595549e-01,  6.78913563e-01,  6.75790695e-02,
        2.89119399e-01,  6.31288226e-01, -1.45715582e+00, -3.19671216e-01,
       -4.70372654e-01, -6.38877848e-01, -2.75142251e-01,  1.49494131e+00,
       -8.65831116e-01,  9.68278355e-01, -1.68286977e+00, -3.34885030e-01,
        1.62753065e-01,  5.86222331e-01,  7.11226580e-01,  7.93347235e-01,
       -3.48725072e-01, -4.62351793e-01,  8.57975881e-01, -1.91304325e-01,
       -1.27568632e+00, -1.13328721e+00, -9.19452286e-01,  4.97160744e-01,
        1.42425736e-01,  

In [121]:
a = np.arange(1, 4)
b = np.arange(4, 7)
c = np.arange(7, 10)
a, b, c

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [122]:
p = np.arange(1, 7).reshape(2, 3)
q = np.arange(11, 17).reshape(2, 3)
r = np.arange(21, 27).reshape(2, 3)
p, q, r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [123]:
np.vstack( (a, b, c) )

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [124]:
np.vstack( (p, q, r) )

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [125]:
np.hstack( (a, b, c) )

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
p, q, r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [127]:
np.hstack( (p, q, r) )

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [128]:
a, b, c

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [129]:
np.column_stack((a, b, c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [130]:
np.column_stack((p, q, r))

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [131]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
np.concatenate((a, b, c), axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
np.concatenate((a, b, c), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [134]:
np.concatenate((a, b, c), axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
np.concatenate((a, b, c), axis=-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
p, q, r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [137]:
np.concatenate((p, q, r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [138]:
np.concatenate((p, q, r), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [139]:
np.concatenate((p, q, r), axis=1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [140]:
np.concatenate((p, q, r), axis=-1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [141]:
np.concatenate((p, q, r), axis=None)

array([ 1,  2,  3,  4,  5,  6, 11, 12, 13, 14, 15, 16, 21, 22, 23, 24, 25,
       26])

In [142]:
np.c_[a, b, c]

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [143]:
np.column_stack( (a, b, c) )

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [144]:
np.column_stack( [a, b, c] )

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [145]:
np.column_stack( a, b, c )

TypeError: column_stack() takes 1 positional argument but 3 were given

In [146]:
np.c_[p, q, r]

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [147]:
np.c_[p, q, r]

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [148]:
np.r_[a, b, c]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [149]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [150]:
np.r_[p, q, r]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [151]:
np.vstack( (p, q, r) )

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])